CHANGELOG.md, kas/distro/omnect-os.yaml, kas/distro/poky.yaml, kas/machine/phytec/phytec.yaml, kas/machine/rpi/rpi.yaml
- updated poky to 4.0.11
- updated meta-openembedded to latest kirkstone HEAD
- updated meta-swupdate to latest kirkstone HEAD
- updated meta-phytec to latest kirkstone HEAD
- updated meta-freescale to latest kirkstone HEAD
- updated meta-raspberrypi to latest kirkstone HEAD
=> poky 4.0.11

CHANGELOG.md, recipes-omnect/omnect-base-files/omnect-base-files.bb, recipes-omnect/omnect-base-files/omnect-base-files/etc/profile.d/tpm2tools.sh, recipes-omnect/omnect-base-files/omnect-base-files/usr/bin/omnect_get_dps_tpm_enrollment.sh, recipes-omnect/omnect-device-service/omnect-device-service_0.13.2.bb
=> merge kirkstone into next

CHANGELOG.md, dynamic-layers/virtualization/recipes-azure-iot/iotedge/aziot-edged/aziot-edged-1.4.21.inc, dynamic-layers/virtualization/recipes-azure-iot/iotedge/aziot-edged/aziot-edged_1.4.21.bb, dynamic-layers/virtualization/recipes-azure-iot/iotedge/iotedge/iotedge-1.4.21.inc, dynamic-layers/virtualization/recipes-azure-iot/iotedge/iotedge/iotedge_1.4.21.bb, recipes-azure-iot/azure-identityd/aziot-identityd_1.4.6.bb, recipes-azure-iot/do-client-sdk/do-client-sdk_git.bb, recipes-azure-iot/do-client/do-client_git.bb
- iot-identity-service: bumped to 1.4.6
- iotedge: bumped to 1.4.21
- do-client: bumped to 1.1.0
=> multiple updates

CHANGELOG.md, recipes-omnect/omnect-device-service/omnect-device-service_0.14.5.bb
fixes error string in results of direct methods
=> omnect-device-service: bumped to 0.14.5 

CHANGELOG.md, recipes-omnect/omnect-device-service/omnect-device-service/omnect-device-service.tmpfilesd, recipes-omnect/omnect-device-service/omnect-device-service_0.14.8.bb
- fixes ssh_tunnel feature and removed ssh_handling feature
=> omnect-device-service: bumped to 0.14.8

CHANGELOG.md, recipes-omnect/initrdscripts/omnect-os-initramfs/flash-mode-2, recipes-omnect/initrdscripts/omnect-os-initramfs/grub-sh
fixed filesystem problems of boot partition for u-boot devices
welotec eg500: fixed factory-reset mode in case boot partition fsck return an error
=> fix initramfs flash-mode-2 and factory-reset mode: 

CHANGELOG.md, recipes-omnect/omnect-device-service/omnect-device-service_0.14.13.bb, recipes-omnect/omnect-device-service/omnect-device-service_0.14.14.bb
- prolonging watchdog timeout while validating firmware update
- configurable azure-iot-sdk-c do_work frequency via enironment variable AZURE_SDK_DO_WORK_FREQUENCY_IN_MS [1..100]
=> omnect-device-service update to 0.14.14:

conf/machine/include/rpi.inc, dynamic-layers/raspberrypi/recipes-bsp/u-boot/u-boot_%.bbappend
corrected rpi bootloader version computation by adding missing rpi
firmware recipe files
=> fix(rpi): corrected bootloader version computation

recipes-omnect/omnect-device-service/omnect-device-service_0.18.1.bb
omnect-device-service 0.18.1 can handle failures related to BadCredentials
=> chore(omnect-device-service): bump to 0.18.1

recipes-azure-iot/azure-identityd/aziot-identityd/aziot-identityd-precondition.service
fixed race against network-online target, which led to timeouts of running iotedge (cli)
=> fix(aziot-identity-precondition): fixed race against network-online target

recipes-azure-iot/iot-hub-device-update/iot-hub-device-update/omnect_1.1.0.patch, recipes-omnect/omnect-device-service/omnect-device-service_0.20.3.bb
bump omnect-device-service to 0.20.3 to deal with new consent_conf.json file
=> feat(iot-hub-device-update):  add handling to remove a user consent on a failed update

recipes-omnect/omnect-device-service/omnect-device-service_0.22.4.bb
https://github.com/omnect/omnect-device-service/pull/106
=> chore(omnect-device-service): bump to 0.22.4

recipes-omnect/omnect-device-service/omnect-device-service_0.25.0.bb
- https://github.com/omnect/omnect-device-service/pull/109
- https://github.com/omnect/omnect-device-service/pull/110
=> chore(omnect-device-service): bumped to 0.25.0 

recipes-omnect/omnect-device-service/omnect-device-service_0.28.0.bb
https://github.com/omnect/omnect-device-service/pull/116
=> chore(omnect-device-service): bump to 0.28.0 

recipes-omnect/omnect-device-service/omnect-device-service_0.28.3.bb
https://github.com/omnect/omnect-device-service/pull/122
=> chore(omnect-device-service): bumped to 0.28.3

recipes-omnect/omnect-device-service/omnect-device-service_0.29.0.bb
https://github.com/omnect/omnect-device-service/pull/121
=> chore(omnect-device-service): bumped to 0.29.0

recipes-omnect/omnect-device-service/omnect-device-service_0.30.4.bb
https://github.com/omnect/omnect-device-service/pull/135
=> chore: bumped omnect-device-service to 0.30.4

recipes-omnect/omnect-device-service/omnect-device-service_0.34.0.bb
https://github.com/omnect/omnect-device-service/pull/144
=> chore(omnect-device-service): bump to 0.34.0

recipes-omnect/omnect-device-service/omnect-device-service_0.35.0.bb
report current reboot reason https://github.com/omnect/meta-omnect/pull/574
=> chore(omnect-device-service): bump to 0.35.0

recipes-connectivity/wpa-supplicant/wpa-supplicant/wpa_supplicant@.service
This is done with the intention to tackle arrakis mk4 sporadic start-up issue with Atheros chip.
=> refactor(wpa_supplicant): added automatic periodic (5s) restart upon failure for 120s
