- conf/machine/include/rpi.inc
- set `RuntimeWatchdogSec` to 10sec - less then max possible 15sec
- set `RebootWatchdogSec` to a more meaningful value  of 3min
> fix(rpi): systemd: set more meaningful hw watchdog configuration values

- conf/machine/include/rpi.inc
- recipes-bsp/u-boot/u-boot_%.bbappend
redundant-env-fragment.cfg is generated during build from redundant-env-fragment.cfg.template
> fix(u-boot): don't use redundant-env-fragment.cfg for bootloader checksum computation

- conf/machine/include/rpi.inc
- dynamic-layers/raspberrypi/recipes-bsp/rpi-bootfiles/rpi-bootfiles.bbappend
- dynamic-layers/raspberrypi/recipes-bsp/u-boot/u-boot_%.bbappend
so that device tree files and firmware is in sync with kernel update from
https://github.com/agherzan/meta-raspberrypi/pull/1257
(fixes boot problems, were devices were stuck in rpi bootloader)
> fix(rpi): update rpi-bootfiles to 1.20230509~buster

- recipes-azure-iot/iot-hub-device-update/iot-hub-device-update/omnect_1.1.0.patch
in case we already signaled the failed state, then we expect that retry or a new update will be present and the download process continues.
Additional we fixed the ignore duplicate deployment workflow to set manually the module twin state back to "idle" to signal  a successful update.
> fix(iot-hub-device-update): retry handling for failed update

- recipes-connectivity/openssh/openssh_%.bbappend
We use the device id as principal for the ssh tunnel user. Until now we therefore would inject a device id into the file. However, sshd can itself retrieve this information via the AuthorizedPrincipalsCommand. With this we adjust the configuration to use the "omnect_get_deviceid.sh" script so that sshd can retrieve its config itself.
> feat(ssh): let sshd determine ssh tunnel principal

- recipes-omnect/omnect-device-service/omnect-device-service.inc
Currently, the modem_info feature does not work reliably on all target platforms. This has the effect that the omnect-device-service fails to start. With this commit we disable the feature until the problem has been resolved.
> fix(omnect-device-service): disable broken modem_info feature

- recipes-omnect/wifi-commissioning-gatt-service/wifi-commissioning-gatt-service_0.4.0.bb
Default BT beacon name changed from DmWifiConfig to omnectWifiConfig and can also now be overridden via environment.
For full details see https://github.com/omnect/wifi-commissioning-gatt-service/pull/26.
> chore(wifi-commissioning-gatt-service): update from 0.3.10 to 0.4.0

- recipes-omnect/omnect-device-service/omnect-device-service.inc
- recipes-omnect/omnect-device-service/omnect-device-service_0.19.1.bb
We bump the version of the omnect-device-service to 0.19.1 to reenable modemmanager support.
> fix(omnect-device-service): re-enable modemmanager support

- recipes-azure-iot/iot-hub-device-update/iot-hub-device-update/omnect_1.1.0.patch
Mismatch of printf type format string and provided argument in json file generation of extension handling caused SHA256 hash to be invalid (value "(null)").
> fix(iot-hub-device-update): extension loading failed due to invalid SHA256 hash in json files

- classes/omnect_bootloader_versioning.bbclass
feat: enabled disabling bootloader version check by setting `OMNECT_BOOTLOADER_VERSION_CHECK_DISABLE=1`
> feat: enabled disabling bootloader version check

- kas/distro/oe.yaml
- kas/distro/omnect-os.yaml
- kas/machine/phytec/phytec.yaml
- kas/machine/x86_64/genericx86-64.yaml
updated openembedded-core + bitbake to yocto-4.0.20
updated meta-openembedded to latest kirkstone head
updated meta-virtualization to latest kirkstone head
updated meta-phytec to latest kirkstone head
updated meta-freescale to latest kirkstone head
updated meta-yocto repo to latest kirkstone head
> chore: update to yocto 4.0.20

- dynamic-layers/virtualization/recipes-containers/docker/docker-moby/0001-daemon-overlay2-Write-layer-metadata-atomically.patch
- dynamic-layers/virtualization/recipes-containers/docker/docker-moby_git.bbappend
During power cycle tests, we have found multiple sporadically issues in case docker image pull operations and a device power cut.
Similar issues are reported here (https://github.com/moby/moby/issues/42964) and a fix was provided here (https://github.com/moby/moby/pull/46471).
> fix(docker): add handling to improve docker image pull operation during power cut

- recipes-bsp/u-boot/bootloader-versioned.bb
Added inheritance of class omnect_bootloader_versioning to recipe to hopefully yield complete dependencies for proper rebuild of versioned bootloader artefact also for 3rd party machines contained is extra meta layers.
> fix(bootloader-versioned): fix attempt for wrong artefact generation

- classes/omnect-device-service.bbclass
- recipes-azure-iot/azure-identityd/aziot-identityd/iot-identity-service.conf
- recipes-omnect/omnect-device-service/omnect-device-service_0.22.0.bb
In order to allow reuse of device identity secret:
- give read access to /var/lib/aziot/certd/certs/* to omnect-device-service and omnect-device-socket user
- give read access to /var/lib/aziot/keyd/keys/* to omnect-device-service and omnect-device-socket user
Related PR's: https://github.com/omnect/omnect-ui/pull/8 and https://github.com/omnect/omnect-device-service/pull/98
> chore(omnect-device-service): bump to 0.22.0 and extend privileges

- recipes-omnect/omnect-device-service/omnect-device-service_0.22.1.bb
This reverts commit a7534db8ae2f9aba93b3a32610e2d8da8d5f0f8c.
> revert: chore(omnect-device-service): bump to 0.22.2 (#490)

- dynamic-layers/virtualization/recipes-containers/docker/docker-moby_git.bbappend
During shutdown or reboot of an iotedge device, the iotedge component stops running docker containers. This works only in case docker and containerd are still running.
> fix(shutdown): add missing systemd dependency containerd in docker.service

- README.md
- recipes-omnect/bootloader_env/bootloader-env/bootloader_env_grub.sh
- recipes-omnect/bootloader_env/bootloader-env/bootloader_env_u-boot.sh
- recipes-omnect/initrdscripts/omnect-os-initramfs/factory-reset
- preserve array is now mandatory
- post hook to unmount filesystems so the factory-reset module doesn't interfere with the fsmount module
> refactor(factory-reset): initramfs: preserve array is now mandatory

- classes/omnect_bootloader_versioning.bbclass
- conf/machine/genericx86-64.extra.conf
- conf/machine/include/phytec-imx8mm.inc
- conf/machine/include/rpi.inc
- doc/Variables_Glossary.md
bootloader_versioning.bbclass now explicitly uses `OMNECT_BOOTLOADER_RECIPE_PATH`
to prevent collisions when computing `OMNECT_BOOTLOADER_CHECKSUM`
> refactor(bootloader): bootloader_versioning.bbclass improvements

- kas/distro/oe.yaml
- kas/distro/omnect-os.yaml
- kas/machine/phytec/phytec.yaml
- kas/machine/x86_64/genericx86-64.yaml
- updated openembedded-core + bitbake to yocto-4.0.23
- updated meta-security to latest kirkstone head
- updated meta-virtualization to latest kirkstone head
- updated meta-phytec to latest kirkstone head
- updated meta-yocto repo to latest kirkstone head
> chore: update to yocto 4.0.23

- conf/distro/include/omnect-os-distro.conf
- got rid of image dependencies to bzip2, lzo, zstd
- restricted dependencies to python3. 
We can't get rid of python3, because it is a build dependency of libxml2 and gobject-introspection. We don't use gobject-introspection and don't have it set in `DISTRO_FEATURES`, but avahi und polkit depend on it anyway.
> refactor(omnect-os-image): revisited dependencies to python and compression libs

- recipes-omnect/omnect-device-service/omnect-device-service_0.28.3.bb
https://github.com/omnect/omnect-device-service/pull/122
merge back release fixes from kirkstone to main
---------
> chore(omnect-device-service): bumped to 0.28.3 (#525)

- recipes-omnect/omnect-device-service/omnect-device-service/omnect-device-service.tmpfilesd
This resolves an issue with the systemd-tmpfilesd config. With the current config, systemd-tmpfilesd would update the files in the wrong order and then refuse to adjust the ca file owner. Instead, we first adjust the owner recursively, and then adjust the file permissions after that.
> fix(omnect-device-service): error to update ssh ca

- kas/distro/oe.yaml
- kas/distro/omnect-os.yaml
- kas/machine/phytec/phytec.yaml
- kas/machine/x86_64/genericx86-64.yaml
- updated openembedded-core + bitbake to yocto-4.0.24
- updated meta-openembedded to latest kirkstone head
- updated meta-phytec to latest kirkstone head
- updated meta-yocto repo to latest kirkstone head
> chore: update to yocto 4.0.24

- conf/distro/include/omnect-os-distro.conf
Note: we use a limited polkit rule set, there are limitations when using
duktape: https://git.openembedded.org/meta-openembedded/tree/meta-oe/recipes-extended/polkit/polkit_124.bb?h=scarthgap#n33
> feat(polkit): use smaller and faster javascript engine duktape vs mozjs

- kas/distro/oe.yaml
- kas/distro/omnect-os.yaml
- kas/machine/phytec/phytec.yaml
- kas/machine/x86_64/genericx86-64.yaml
- updated openembedded-core + bitbake to yocto-5.0.7
- updated meta-openembedded to latest scarthgap head
- updated meta-freescale to latest scarthgap head
- updated meta-yocto repo to latest head
> chore: update to yocto 5.0.7

- recipes-omnect/omnect-device-service/omnect-device-service_0.30.5.bb
See https://github.com/omnect/omnect-device-service/pull/137 for more details.
> fix(ssh-tunnel): bump omnect-device-service to 0.30.5 to fix high cpu load on establishing a tunnel

- conf/machine/include/phytec-imx8mm.inc
- dynamic-layers/phytec/recipes-bsp/u-boot/u-boot/omnect_env.patch
- kas/distro/oe.yaml
- kas/distro/omnect-os.yaml
- kas/machine/phytec/phytec.yaml
- kas/machine/x86_64/genericx86-64.yaml
- updated openembedded-core + bitbake to yocto-4.0.25
- updated meta-swupdate to latest kirkstone head
- updated meta-virtualization to latest kirkstone head
- updated meta-phytec to latest kirkstone head
- updated meta-yocto repo to latest kirkstone head
> chore: update to yocto 4.0.25

- README.md
- recipes-omnect/initrdscripts/omnect-os-initramfs/common-sh
- recipes-omnect/initrdscripts/omnect-os-initramfs/omnect-device-service-setup
- fixed fsck state when multiple partitions were fixed by fsck
- also fixed problem with EFI fsck handling for boot partition
- added documentation for filesystem checks
> fix(omnect-os-initramfs.json): fixed fsck state when multiple partitions were fixed by fsck

- kas/machine/rpi/rpi.yaml
> chore(rpi): update to latest meta-raspberrypi scarthgap head

- recipes-omnect/omnect-device-service/omnect-device-service_0.32.3.bb
https://github.com/omnect/omnect-device-service/pull/142 fixes watchdog timeout while loading local update package
> chore(omnect-device-service): bump to 0.32.3

- recipes-omnect/omnect-device-service/omnect-device-service_0.33.0.bb
https://github.com/omnect/omnect-device-service/pull/143
> chore(omnect-device-service): bump to 0.33.0 which enables its webservice interface by default

- conf/machine/genericx86-64.extra.conf
- recipes-bsp/grub/grub-efi_%.bbappend
- recipes-omnect/bootloader_env/bootloader-env/bootloader_env_grub.sh
- recipes-omnect/grub-cfg/grub-cfg/grub.cfg.in
- recipes-omnect/initrdscripts/omnect-os-initramfs/grub-sh
CI/CD tests showed that intentionally crashing the system or causing a power cut can cause the system to get stuck in initramfs due to an empty grub environment file.
Therefore ensure that whenever the grub environment gets touched the change is made persistent via a subsequent sync.
Additionally enable grub echo module so that console output during boot works.
> fix(genericx86): improve boot robustness

- conf/machine/include/rpi.inc
- kas/distro/oe.yaml
- kas/distro/omnect-os.yaml
- kas/machine/phytec/phytec.yaml
- kas/machine/rpi/rpi.yaml
- kas/machine/x86_64/genericx86-64.yaml
- updated openembedded-core + bitbake to yocto-4.0.26
- updated meta-openembedded to latest kirkstone head
- updated meta-virtualization to latest kirkstone head
- updated meta-phytec to latest kirkstone head
- updated meta-freescale to latest kirkstone head
- updated meta-imx to latest kirkstone-5.15.71-2.2.2 head
- updated meta-raspberrypi to latest kirkstone head
- updated meta-yocto repo to latest kirkstone head
- adapted `OMNECT_BOOTLOADER_CHECKSUM_EXPECTED` for raspberrypi since openembedded-core fixed multiple u-boot cve's
note: a bootloader update is enforced for raspberrypi
> chore: update to yocto 4.0.26

- recipes-connectivity/networkmanager/files/NetworkManager.conf
Previous NetworkManager.conf defined the managed (LTE) interfaces to have names either prefixed with wwan or cdc-wdm.
However, in scarthgap such interfaces might have their topological name (specifying the position hardware-wise), e.g. `wwp0s21f0u8i4`.
In any case, interface names starting with `ww` are intended for WWAN interfaces like LTE modems (see man page for `systemd.net-naming-scheme(7)`), so use this prefix to determine WWAN interfaces to be managed by NetworkManager.
> fix(NetworkManager): names of WWAN interfaces to be managed were too strictly defined

- conf/distro/include/omnect-os-distro.conf
- removed shared-mime-info as dependency from glib2.0
- removed sqlite and btrfs-tools as dependencies from docker
> chore(dependencies): remove unused dependencies

- conf/machine/include/phytec-imx8mm.inc
- conf/machine/include/rpi.inc
- dynamic-layers/raspberrypi/recipes-bsp/bootloader-versioned/bootloader-versioned.bbappend
- kas/distro/oe.yaml
- kas/distro/omnect-os.yaml
- kas/machine/phytec/phytec.yaml
- kas/machine/rpi/rpi.yaml
- kas/machine/x86_64/genericx86-64.yaml
- updated openembedded to yocto-5.0.10
- updated meta-openembedded to latest scarthgap head
- updated meta-swupdate to latest scarthgap head
- updated meta-phytec to latest scarthgap head
- updated meta-freescale to latest scarthgap head
- updated meta-raspberrypi to latest scarthgap head
- updated meta-yocto repo to latest scarthgap head
**note**: this update includes a bootloader update for phytec tauri-l  (https://github.com/phytec/meta-phytec/commit/a7c035bca24cde242d046ae4d91fe143d1181c15).
> chore: update to yocto 5.0.10

- README.md
- conf/machine/genericx86-64.extra.conf
- doc/efi_secure_boot.md
- recipes-bsp/grub/grub-efi/efi-secure-boot.inc
- recipes-bsp/grub/grub-efi_%.bbappend
- grub: ensure LockDown.efi is booted
- doc: added documentation for secure boot certificate provisioning
> fix(grub): refactored secure boot provisioning handling
